version: '3.8'

services:
  traefik:
    image: traefik:v2.11.2
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=admin@integraicontador.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.fields.names.StartUTC=true"
      - "--accesslog.fields.names.Duration=true"
      - "--accesslog.fields.names.ClientUsername=true"
      - "--accesslog.fields.names.RequestHost=true"
      - "--accesslog.fields.names.RequestPath=true"
      - "--accesslog.fields.names.RequestMethod=true"
      - "--accesslog.fields.names.RequestProtocol=true"
      - "--accesslog.fields.names.DownstreamStatus=true"
      - "--accesslog.fields.names.RouterName=true"
      - "--accesslog.fields.names.ServiceName=true"
      - "--accesslog.fields.names.ServiceURL=true"
      - "--accesslog.fields.names.DownstreamStatus=true"
      - "--accesslog.fields.names.DownstreamHost=true"
      - "--accesslog.fields.names.DownstreamResponseSize=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt
      - traefik_data:/etc/traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    image: frontapi_web
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`api.integraicontador.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.middlewares=web-redirect"
      - "traefik.http.middlewares.web-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.web.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.web-compress.compress=true"
      - "traefik.http.routers.web.middlewares=web-compress"
      - "traefik.http.middlewares.web-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.web-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.web-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.web-headers.headers.stsPreload=true"
      - "traefik.http.routers.web.middlewares=web-headers"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.services.web.loadbalancer.passHostHeader=true"
      - "traefik.http.services.web.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.web.loadbalancer.sticky.cookie.name=frontapi_session"
      - "traefik.http.services.web.loadbalancer.sticky.cookie.secure=true"
      - "traefik.http.services.web.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.web.loadbalancer.sticky.cookie.sameSite=strict"
    volumes:
      - app_data:/app
      - nfe_keys_data:/app/nfe_keys.txt
      - url_cache_data:/app/url_cache.json
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  letsencrypt_data:
  traefik_data:
  app_data:
  nfe_keys_data:
  url_cache_data: 
